"""Tests for BinaryWriter.caption() and section manual generation."""

import pytest
from binary_master import BinaryWriter, Writer, Endian, UInt16, UInt8, binary_struct
from binary_master.manual import generate_manual


@binary_struct
class SimplePayload:
    cmd: UInt8
    value: UInt16


def test_caption_basic_and_chaining():
    """Test setting and clearing captions with method chaining."""
    writer = BinaryWriter()
    assert not hasattr(writer, "write_manual")
    assert writer.current_caption is None

    writer.caption("Header").write_uint32(0x12345678, name="magic")
    assert writer.current_caption == "Header"
    assert writer.entries[0].caption == "Header"

    writer.write_uint16(1, name="version")
    assert writer.entries[1].caption == "Header"

    # Change caption
    writer.caption("Payload").write_uint8(42, name="data")
    assert writer.current_caption == "Payload"
    assert writer.entries[2].caption == "Payload"

    # Clear caption
    writer.caption("").write_uint8(0, name="tail")
    assert writer.current_caption is None
    assert writer.entries[3].caption is None

    # Clear caption with None
    writer.caption("Temp").caption(None).write_uint8(9, name="end")
    assert writer.current_caption is None
    assert writer.entries[4].caption is None


def test_writer_alias():
    """Test Writer alias for BinaryWriter."""
    assert Writer is BinaryWriter
    w = Writer()
    w.caption("Test").write_uint8(1)
    assert w.entries[0].caption == "Test"


def test_caption_manual_generation():
    """Test manual generation with sections and headings divided by captions."""
    writer = BinaryWriter(default_endian=Endian.LITTLE)
    writer.caption("File Header")
    writer.write_uint32(0xCAFEBABE, name="magic", desc="Magic header identifier")
    writer.write_uint16(2, name="version", desc="Format version")

    writer.caption("Payload Block")
    writer.write_cstring("Hello", name="greeting", desc="Greeting text")
    writer.write_uint16(100, name="checksum", desc="Payload checksum")

    md = generate_manual(writer.entries, title="Captioned Binary Spec")

    # Structure Diagram should have subgraphs for each caption
    assert "subgraph SG_File_Header" in md
    assert '["File Header"]' in md
    assert "subgraph SG_Payload_Block" in md
    assert '["Payload Block"]' in md

    # Memory Layout Table should have section headings
    assert "## Memory Layout Table" in md
    assert "### File Header\n" in md
    assert "### Payload Block\n" in md

    # When include_section_offsets=True, offset ranges are added
    md_offsets = generate_manual(writer.entries, include_section_offsets=True)
    assert '["File Header (0x0000 - 0x0006, 6B)"]' in md_offsets
    assert "### File Header (0x0000 - 0x0006, 6B)" in md_offsets

    # Entries in table
    assert "| `0x0000` | 0 | 4 | `magic` | `UInt32` | Little | Magic header identifier |" in md
    assert "| `0x0004` | 4 | 2 | `version` | `UInt16` | Little | Format version |" in md
    assert "| `0x0006` | 6 | 6 | `greeting` | `CString` | - | Greeting text |" in md
    assert "| `0x000C` | 12 | 2 | `checksum` | `UInt16` | Little | Payload checksum |" in md

    # When include_values=True, Value / Preview is present
    md_val = generate_manual(writer.entries, include_values=True)
    assert "| `0x0000` | 0 | 4 | `magic` | `UInt32` | Little | `3405691582 (0xCAFEBABE)` | Magic header identifier |" in md_val


def test_caption_with_japanese_text():
    """Test captions with Japanese text, ensuring valid Mermaid subgraph IDs and clean headings."""
    writer = BinaryWriter()
    writer.caption("ヘッダー情報")
    writer.write_uint16(0x5A5A, name="id")

    writer.caption("データ本体")
    writer.write_uint32(12345, name="count")

    md = generate_manual(writer.entries, title="日本語テスト")

    # Japanese label in subgraph (clean by default)
    assert '["ヘッダー情報"]' in md
    assert '["データ本体"]' in md

    # Headings in layout table (clean by default)
    assert "### ヘッダー情報\n" in md
    assert "### データ本体\n" in md

    # With include_section_offsets=True
    md_offsets = generate_manual(writer.entries, include_section_offsets=True)
    assert '["ヘッダー情報 (0x0000 - 0x0002, 2B)"]' in md_offsets
    assert "### ヘッダー情報 (0x0000 - 0x0002, 2B)" in md_offsets


def test_caption_with_binary_struct():
    """Test that writer.caption() applies to entries generated by write_struct."""
    writer = BinaryWriter()
    writer.caption("Command Packet")
    payload = SimplePayload(cmd=0x01, value=500)
    writer.write_struct(payload)

    assert writer.entries[0].caption == "Command Packet"
    assert writer.entries[1].caption == "Command Packet"

    md = generate_manual(writer.entries)
    assert "### Command Packet\n" in md

    md_off = generate_manual(writer.entries, include_section_offsets=True)
    assert "### Command Packet (0x0000 - 0x0003, 3B)" in md_off


def test_set_caption_direct():
    """Test set_caption directly sets caption, description and spec_count."""
    writer = BinaryWriter()
    writer.set_caption("DirectHeader", desc="Header section", spec_count=1)
    assert writer.current_caption == "DirectHeader"
    assert writer.current_caption_desc == "Header section"
    assert writer.current_caption_spec_count == 1
    assert writer.current_caption_repeat == 1

    writer.write_uint32(0x12345678, name="magic", desc="Magic identifier")
    assert writer.entries[0].caption == "DirectHeader"
    assert writer.entries[0].caption_desc == "Header section"


def test_set_caption_context_manager_offset_table():
    """Test with writer.set_caption(...) scoping and offset_table inheritance."""
    writer = BinaryWriter()
    writer.write_uint32(0xCAFE, name="file_magic")

    with writer.set_caption("offsets", desc="Table of chunk offsets", spec_count="num_chunk"):
        assert writer.current_caption == "offsets"
        assert writer.current_caption_desc == "Table of chunk offsets"
        assert writer.current_caption_repeat == "num_chunk"
        table = writer.write_offset_table(count=3)

    # After exiting with block, caption and repeat are restored!
    assert writer.current_caption is None
    assert writer.current_caption_repeat is None

    # Write payload outside offset table
    for i in range(3):
        pos = writer.tell()
        table[i] = pos
        writer.write_cstring(f"CHUNK_{i}", name=f"chunk_{i}")

    # Entries in table have the offset caption and repeat
    for i in range(1, 4):
        assert writer.entries[i].caption == "offsets"
        assert writer.entries[i].caption_repeat == "num_chunk"

    # Entries outside table have None caption
    assert writer.entries[4].caption is None

    # Generate manual: check offsets are aggregated
    md = generate_manual(writer.entries, title="Offset Archive")
    assert "### offsets\n" in md
    assert "Table of chunk offsets" in md
    assert "num_chunk" in md
    assert "offsets[i]" in md
    assert 'subgraph SG_offsets ["offsets 🔁 xnum_chunk"]' in md

    md_off = generate_manual(writer.entries, title="Offset Archive", include_section_offsets=True)
    assert "### offsets (0x0004 - 0x0010, 12B)" in md_off
    assert 'subgraph SG_offsets ["offsets 🔁 xnum_chunk (0x0004 - 0x0010, 12B)"]' in md_off


def test_set_caption_context_manager_struct_loop():
    """Test with writer.set_caption(...) with repeated struct writes."""
    writer = BinaryWriter()
    items = [SimplePayload(cmd=i, value=100 + i) for i in range(4)]

    with writer.set_caption("PayloadList", desc="List of commands", spec_count="cmd_count"):
        for item in items:
            writer.write_struct(item)

    assert writer.current_caption is None
    assert writer.current_caption_repeat is None

    md = generate_manual(writer.entries, title="Struct Loop")
    assert "### PayloadList\n" in md
    assert "List of commands" in md
    assert "cmd_count" in md
    assert 'subgraph SG_PayloadList ["PayloadList 🔁 xcmd_count"]' in md

    md_off = generate_manual(writer.entries, title="Struct Loop", include_section_offsets=True)
    assert "### PayloadList (0x0000 - 0x000C, 12B)" in md_off


def test_set_caption_nested():
    """Test nested set_caption context managers restore previous states correctly."""
    writer = BinaryWriter()
    writer.set_caption("Outer", desc="Outer desc", spec_count=5)

    with writer.set_caption("Inner", desc="Inner desc", spec_count="inner_count"):
        assert writer.current_caption == "Inner"
        assert writer.current_caption_desc == "Inner desc"
        assert writer.current_caption_repeat == "inner_count"
        writer.write_uint16(0xAA, name="inner_field")

    # Restored to Outer
    assert writer.current_caption == "Outer"
    assert writer.current_caption_desc == "Outer desc"
    assert writer.current_caption_repeat == 5
    writer.write_uint16(0xBB, name="outer_field")

    assert writer.entries[0].caption == "Inner"
    assert writer.entries[1].caption == "Outer"


def test_builder_set_caption():
    """Test BinaryBuilder.set_caption with context manager."""
    from binary_master import BinaryBuilder

    builder = BinaryBuilder(title="Builder Spec")
    with builder.set_caption("HeaderSection", desc="Header details", spec_count=1):
        builder.add_field("magic", "UInt32", 4, desc="Magic identifier")

    with builder.set_caption("ChunkOffsets", desc="Table of offsets", spec_count="num_chunks"):
        builder.add_field("offset", "UInt32", 4, desc="Chunk offset")

    md = builder.to_markdown()
    assert "HeaderSection" in md
    assert "ChunkOffsets" in md
