"""Tests for BinaryWriter.caption() and section manual generation."""

import pytest
from binary_master import BinaryWriter, Writer, Endian, UInt16, UInt8, binary_struct
from binary_master.manual import generate_manual


@binary_struct
class SimplePayload:
    cmd: UInt8
    value: UInt16


def test_caption_basic_and_chaining():
    """Test setting and clearing captions with method chaining."""
    writer = BinaryWriter()
    assert not hasattr(writer, "write_manual")
    assert writer.current_caption is None

    writer.caption("Header").write_uint32(0x12345678, name="magic")
    assert writer.current_caption == "Header"
    assert writer.entries[0].caption == "Header"

    writer.write_uint16(1, name="version")
    assert writer.entries[1].caption == "Header"

    # Change caption
    writer.caption("Payload").write_uint8(42, name="data")
    assert writer.current_caption == "Payload"
    assert writer.entries[2].caption == "Payload"

    # Clear caption
    writer.caption("").write_uint8(0, name="tail")
    assert writer.current_caption is None
    assert writer.entries[3].caption is None

    # Clear caption with None
    writer.caption("Temp").caption(None).write_uint8(9, name="end")
    assert writer.current_caption is None
    assert writer.entries[4].caption is None


def test_writer_alias():
    """Test Writer alias for BinaryWriter."""
    assert Writer is BinaryWriter
    w = Writer()
    w.caption("Test").write_uint8(1)
    assert w.entries[0].caption == "Test"


def test_caption_manual_generation():
    """Test manual generation with sections and headings divided by captions."""
    writer = BinaryWriter(default_endian=Endian.LITTLE)
    writer.caption("File Header")
    writer.write_uint32(0xCAFEBABE, name="magic", desc="Magic header identifier")
    writer.write_uint16(2, name="version", desc="Format version")

    writer.caption("Payload Block")
    writer.write_cstring("Hello", name="greeting", desc="Greeting text")
    writer.write_uint16(100, name="checksum", desc="Payload checksum")

    md = generate_manual(writer.entries, title="Captioned Binary Spec")

    # Structure Diagram should have subgraphs for each caption
    assert "subgraph SG_File_Header" in md
    assert '["File Header (0x0000 - 0x0006, 6B)"]' in md
    assert "subgraph SG_Payload_Block" in md
    assert '["Payload Block (0x0006 - 0x000E, 8B)"]' in md

    # Memory Layout Table should have section headings
    assert "## Memory Layout Table" in md
    assert "### File Header (0x0000 - 0x0006, 6B)" in md
    assert "### Payload Block (0x0006 - 0x000E, 8B)" in md

    # Entries in table
    assert "| `0x0000` | 0 | 4 | `magic` | `UInt32` | Little | Magic header identifier |" in md
    assert "| `0x0004` | 4 | 2 | `version` | `UInt16` | Little | Format version |" in md
    assert "| `0x0006` | 6 | 6 | `greeting` | `CString` | - | Greeting text |" in md
    assert "| `0x000C` | 12 | 2 | `checksum` | `UInt16` | Little | Payload checksum |" in md

    # When include_values=True, Value / Preview is present
    md_val = generate_manual(writer.entries, include_values=True)
    assert "| `0x0000` | 0 | 4 | `magic` | `UInt32` | Little | `3405691582 (0xCAFEBABE)` | Magic header identifier |" in md_val


def test_caption_with_japanese_text():
    """Test captions with Japanese text, ensuring valid Mermaid subgraph IDs and clean headings."""
    writer = BinaryWriter()
    writer.caption("ヘッダー情報")
    writer.write_uint16(0x5A5A, name="id")

    writer.caption("データ本体")
    writer.write_uint32(12345, name="count")

    md = generate_manual(writer.entries, title="日本語テスト")

    # Japanese label in subgraph
    assert '["ヘッダー情報 (0x0000 - 0x0002, 2B)"]' in md
    assert '["データ本体 (0x0002 - 0x0006, 4B)"]' in md

    # Headings in layout table
    assert "### ヘッダー情報 (0x0000 - 0x0002, 2B)" in md
    assert "### データ本体 (0x0002 - 0x0006, 4B)" in md


def test_caption_with_binary_struct():
    """Test that writer.caption() applies to entries generated by write_struct."""
    writer = BinaryWriter()
    writer.caption("Command Packet")
    payload = SimplePayload(cmd=0x01, value=500)
    writer.write_struct(payload)

    assert writer.entries[0].caption == "Command Packet"
    assert writer.entries[1].caption == "Command Packet"

    md = generate_manual(writer.entries)
    assert "### Command Packet (0x0000 - 0x0003, 3B)" in md
