//! ============================================================================
//! Network Telemetry Protocol Specification
//! Version: 1.0.0
//! テキスト通信と環境テレメトリ計測パケットを統合したバイナリプロトコル仕様。
//! Automatically generated by binary_master.
//! ============================================================================

#![allow(dead_code, non_camel_case_types, non_snake_case)]

// ============================================================================
// プロトコル概要とスコープ
// ============================================================================
// 本仕様書はネットワークテレメトリプロトコル (NTP-v1) を規定します。
// すべての数値フィールドはリトルエンディアンでエンコードされます。
//
// パケットは固定14バイトの `PacketHeader` から開始し、`msg_type` に応じてペイロードが分岐します：
// - `0x0001`: `TextMessage`
// - `0x0002`: `SensorReport`
//
// また、`flags` の Bit 0 が立っている場合、末尾に 4 バイトの `ChecksumFooter` が付与されます。

// ----------------------------------------------------------------------------
// Section: Header Section
// コンテナ識別固定ヘッダー
// ----------------------------------------------------------------------------

/// Logical Name: `header`
/// 固定14バイトパケットヘッダー
#[repr(C, packed)]
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct PacketHeader {
    pub magic: u32,
    pub version: u16,
    pub msg_type: u16,
    pub payload_size: u32,
    pub flags: u16,
}

// ----------------------------------------------------------------------------
// Section: Header Section
// コンテナ識別固定ヘッダー
// ----------------------------------------------------------------------------

// ----------------------------------------------------------------------------
// Section: Payload Section
// 動的ペイロードブロック
// ----------------------------------------------------------------------------

/// Tag values for choice `payload` (dispatched by `msg_type`).
/// PacketHeader.msg_type による動的分岐
#[repr(u16)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum PayloadTag {
    /// プレーンテキストメッセージ
    TextMessage = 0x01,
    /// マルチチャネル環境センサー計測値
    SensorReport = 0x02,
}

/// プレーンテキストメッセージ
#[repr(C, packed)]
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct TextMessage {
    pub encoding: u16,
    pub text_len: u16,
    pub content: [u8; 16],
}

/// マルチチャネル環境センサー計測値
#[repr(C, packed)]
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct SensorReport {
    pub sensor_id: u32,
    pub temperature: f32,
    pub pressure: f32,
    pub humidity: f32,
}

/// Polymorphic container for choice `payload`.
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum PayloadUnion {
    TextMessage(TextMessage),
    SensorReport(SensorReport),
}

// ----------------------------------------------------------------------------
// Section: Payload Section
// 動的ペイロードブロック
// ----------------------------------------------------------------------------

// ----------------------------------------------------------------------------
// Section: Footer Section
// オプション完全性検証ブロック
// ----------------------------------------------------------------------------

/// Logical Name: `footer`
/// CRC32 チェックサム
///
/// **Condition**: `flags & 0x01 != 0`
#[repr(C, packed)]
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct ChecksumFooter {
    pub crc32: u32,
}

// ----------------------------------------------------------------------------
// Section: Footer Section
// オプション完全性検証ブロック
// ----------------------------------------------------------------------------
