// ============================================================================
// Network Telemetry Protocol Specification
// Version: 1.0.0
// テキスト通信と環境テレメトリ計測パケットを統合したバイナリプロトコル仕様。
// Automatically generated by binary_master.
// ============================================================================

package telemetry

// ============================================================================
// プロトコル概要とスコープ
// ============================================================================
// 本仕様書はネットワークテレメトリプロトコル (NTP-v1) を規定します。
// すべての数値フィールドはリトルエンディアンでエンコードされます。
//
// パケットは固定14バイトの `PacketHeader` から開始し、`msg_type` に応じてペイロードが分岐します：
// - `0x0001`: `TextMessage`
// - `0x0002`: `SensorReport`
//
// また、`flags` の Bit 0 が立っている場合、末尾に 4 バイトの `ChecksumFooter` が付与されます。

// ----------------------------------------------------------------------------
// Section: Header Section
// コンテナ識別固定ヘッダー
// ----------------------------------------------------------------------------

// Logical Name: header
// 固定14バイトパケットヘッダー
type PacketHeader struct {
	Magic uint32
	Version uint16
	MsgType uint16
	PayloadSize uint32
	Flags uint16
}

// ----------------------------------------------------------------------------
// Section: Header Section
// コンテナ識別固定ヘッダー
// ----------------------------------------------------------------------------

// ----------------------------------------------------------------------------
// Section: Payload Section
// 動的ペイロードブロック
// ----------------------------------------------------------------------------

// PayloadTag represents tag values for choice payload (dispatched by msg_type).
// PacketHeader.msg_type による動的分岐
type PayloadTag uint16

const (
	PayloadTagTextMessage PayloadTag = 0x01 // プレーンテキストメッセージ
	PayloadTagSensorReport PayloadTag = 0x02 // マルチチャネル環境センサー計測値
)

// プレーンテキストメッセージ
type TextMessage struct {
	Encoding uint16
	TextLen uint16
	Content [16]uint8
}

// マルチチャネル環境センサー計測値
type SensorReport struct {
	SensorId uint32
	Temperature float32
	Pressure float32
	Humidity float32
}

// Payload is the interface implemented by all variants of choice payload.
type Payload interface {
	IsPayload()
}

func (TextMessage) IsPayload() {}
func (SensorReport) IsPayload() {}

// ----------------------------------------------------------------------------
// Section: Payload Section
// 動的ペイロードブロック
// ----------------------------------------------------------------------------

// ----------------------------------------------------------------------------
// Section: Footer Section
// オプション完全性検証ブロック
// ----------------------------------------------------------------------------

// Logical Name: footer
// CRC32 チェックサム
// Condition: flags & 0x01 != 0
type ChecksumFooter struct {
	Crc32 uint32
}

// ----------------------------------------------------------------------------
// Section: Footer Section
// オプション完全性検証ブロック
// ----------------------------------------------------------------------------
