//! ============================================================================
//! Network Telemetry Protocol Specification
//! Version: 1.0.0
//! Unified binary messaging format supporting text messages and sensor telemetry packets.
//! Automatically generated by binary_master.
//! ============================================================================

#![allow(dead_code, non_camel_case_types, non_snake_case)]

// ============================================================================
// Protocol Overview & Scope
// ============================================================================
// This document specifies the Network Telemetry Protocol (NTP-v1).
// All multi-byte numeric fields are encoded in Little-Endian byte order.
//
// Packets begin with a fixed 14-byte `PacketHeader`. The `msg_type` field dictates
// which payload structure immediately follows:
// - `0x0001`: `TextMessage`
// - `0x0002`: `SensorReport`
//
// If bit 0 of `flags` is set (`flags & 0x01 != 0`), a 4-byte `ChecksumFooter` is appended.

// ----------------------------------------------------------------------------
// Section: Header Section
// Fixed container identification header
// ----------------------------------------------------------------------------

/// Logical Name: `header`
/// Fixed 14-byte packet header
#[repr(C, packed)]
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct PacketHeader {
    /// Signature: 0x4D534750 ('MSGP')
    pub magic: u32,
    /// Protocol version
    pub version: u16,
    /// 1 = Text, 2 = Sensor Data
    pub msg_type: u16,
    /// Length of following payload
    pub payload_size: u32,
    /// Bit 0: Has Checksum Footer
    pub flags: u16,
}

// ----------------------------------------------------------------------------
// Section: Header Section
// Fixed container identification header
// ----------------------------------------------------------------------------

// ----------------------------------------------------------------------------
// Section: Payload Section
// Polymorphic payload block
// ----------------------------------------------------------------------------

/// Tag values for choice `payload` (dispatched by `msg_type`).
/// Dynamic payload dispatched by PacketHeader.msg_type
#[repr(u16)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum PayloadTag {
    /// Human-readable plaintext message payload
    TextMessage = 0x01,
    /// Multi-channel environmental sensor readings
    SensorReport = 0x02,
}

/// Human-readable plaintext message payload
#[repr(C, packed)]
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct TextMessage {
    /// 1 = UTF-8, 2 = ASCII
    pub encoding: u16,
    /// Length of text in bytes
    pub text_len: u16,
    /// Fixed buffer for text
    pub content: [u8; 16],
}

/// Multi-channel environmental sensor readings
#[repr(C, packed)]
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct SensorReport {
    /// Unique sensor ID
    pub sensor_id: u32,
    /// Temperature in Celsius
    pub temperature: f32,
    /// Pressure in hPa
    pub pressure: f32,
    /// Relative humidity (0.0 - 100.0)
    pub humidity: f32,
}

/// Polymorphic container for choice `payload`.
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum PayloadUnion {
    TextMessage(TextMessage),
    SensorReport(SensorReport),
}

// ----------------------------------------------------------------------------
// Section: Payload Section
// Polymorphic payload block
// ----------------------------------------------------------------------------

// ----------------------------------------------------------------------------
// Section: Footer Section
// Optional trailing integrity verification
// ----------------------------------------------------------------------------

/// Logical Name: `footer`
/// Trailing CRC32 checksum verification
///
/// **Condition**: `flags & 0x01 != 0`
#[repr(C, packed)]
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct ChecksumFooter {
    /// IEEE 802.3 CRC32 checksum
    pub crc32: u32,
}

// ----------------------------------------------------------------------------
// Section: Footer Section
// Optional trailing integrity verification
// ----------------------------------------------------------------------------
