// ============================================================================
// Network Telemetry Protocol Specification
// Version: 1.0.0
// テキスト通信と環境テレメトリ計測パケットを統合したバイナリプロトコル仕様。
// Automatically generated by binary_master.
// ============================================================================

using System;
using System.Runtime.InteropServices;

namespace TelemetryProtocol {
    // ========================================================================
    // プロトコル概要とスコープ
    // ========================================================================
    // 本仕様書はネットワークテレメトリプロトコル (NTP-v1) を規定します。
    // すべての数値フィールドはリトルエンディアンでエンコードされます。
    //
    // パケットは固定14バイトの `PacketHeader` から開始し、`msg_type` に応じてペイロードが分岐します：
    // - `0x0001`: `TextMessage`
    // - `0x0002`: `SensorReport`
    //
    // また、`flags` の Bit 0 が立っている場合、末尾に 4 バイトの `ChecksumFooter` が付与されます。

    // ------------------------------------------------------------------------
    // Section: Header Section
    // コンテナ識別固定ヘッダー
    // ------------------------------------------------------------------------

    /// <summary>
    /// Logical Name: header
    /// 固定14バイトパケットヘッダー
    /// </summary>
    [StructLayout(LayoutKind.Sequential, Pack = 1)]
    public struct PacketHeader {
        public uint Magic;
        public ushort Version;
        public ushort MsgType;
        public uint PayloadSize;
        public ushort Flags;
    }

    // ------------------------------------------------------------------------
    // Section: Header Section
    // コンテナ識別固定ヘッダー
    // ------------------------------------------------------------------------

    // ------------------------------------------------------------------------
    // Section: Payload Section
    // 動的ペイロードブロック
    // ------------------------------------------------------------------------

    /// <summary>
    /// Tag values for choice `payload` (dispatched by `msg_type`).
    /// PacketHeader.msg_type による動的分岐
    /// </summary>
    public enum PayloadTag : ushort {
        /// <summary>プレーンテキストメッセージ</summary>
        TextMessage = 0x01,
        /// <summary>マルチチャネル環境センサー計測値</summary>
        SensorReport = 0x02,
    }

    /// <summary>
    /// プレーンテキストメッセージ
    /// </summary>
    [StructLayout(LayoutKind.Sequential, Pack = 1)]
    public struct TextMessage {
        public ushort Encoding;
        public ushort TextLen;
        [MarshalAs(UnmanagedType.ByValArray, SizeConst = 16)]
        public byte[] Content;
    }

    /// <summary>
    /// マルチチャネル環境センサー計測値
    /// </summary>
    [StructLayout(LayoutKind.Sequential, Pack = 1)]
    public struct SensorReport {
        public uint SensorId;
        public float Temperature;
        public float Pressure;
        public float Humidity;
    }

    /// <summary>
    /// Polymorphic union container for choice `payload`.
    /// </summary>
    [StructLayout(LayoutKind.Explicit, Pack = 1)]
    public struct PayloadUnion {
        [FieldOffset(0)] public TextMessage TextMessage;
        [FieldOffset(0)] public SensorReport SensorReport;
    }

    // ------------------------------------------------------------------------
    // Section: Payload Section
    // 動的ペイロードブロック
    // ------------------------------------------------------------------------

    // ------------------------------------------------------------------------
    // Section: Footer Section
    // オプション完全性検証ブロック
    // ------------------------------------------------------------------------

    /// <summary>
    /// Logical Name: footer
    /// CRC32 チェックサム
    /// Condition: flags & 0x01 != 0
    /// </summary>
    [StructLayout(LayoutKind.Sequential, Pack = 1)]
    public struct ChecksumFooter {
        public uint Crc32;
    }

    // ------------------------------------------------------------------------
    // Section: Footer Section
    // オプション完全性検証ブロック
    // ------------------------------------------------------------------------

}