// ============================================================================
// Network Telemetry Protocol Specification
// Version: 1.0.0
// Unified binary messaging format supporting text messages and sensor telemetry packets.
// Automatically generated by binary_master.
// ============================================================================

using System;
using System.Runtime.InteropServices;

namespace TelemetryProtocol {
    // ========================================================================
    // Protocol Overview & Scope
    // ========================================================================
    // This document specifies the Network Telemetry Protocol (NTP-v1).
    // All multi-byte numeric fields are encoded in Little-Endian byte order.
    //
    // Packets begin with a fixed 14-byte `PacketHeader`. The `msg_type` field dictates
    // which payload structure immediately follows:
    // - `0x0001`: `TextMessage`
    // - `0x0002`: `SensorReport`
    //
    // If bit 0 of `flags` is set (`flags & 0x01 != 0`), a 4-byte `ChecksumFooter` is appended.

    /// <summary>
    /// Logical Name: header
    /// Fixed 14-byte packet header
    /// </summary>
    [StructLayout(LayoutKind.Sequential, Pack = 1)]
    public struct PacketHeader {
        /// <summary>Signature: 0x4D534750 ('MSGP')</summary>
        public uint Magic;
        /// <summary>Protocol version</summary>
        public ushort Version;
        /// <summary>1 = Text, 2 = Sensor Data</summary>
        public ushort MsgType;
        /// <summary>Length of following payload</summary>
        public uint PayloadSize;
        /// <summary>Bit 0: Has Checksum Footer</summary>
        public ushort Flags;
    }

    /// <summary>
    /// Tag values for choice `payload` (dispatched by `msg_type`).
    /// Dynamic payload dispatched by PacketHeader.msg_type
    /// </summary>
    public enum PayloadTag : ushort {
        /// <summary>Human-readable plaintext message payload</summary>
        TextMessage = 0x01,
        /// <summary>Multi-channel environmental sensor readings</summary>
        SensorReport = 0x02,
    }

    /// <summary>
    /// Human-readable plaintext message payload
    /// </summary>
    [StructLayout(LayoutKind.Sequential, Pack = 1)]
    public struct TextMessage {
        /// <summary>1 = UTF-8, 2 = ASCII</summary>
        public ushort Encoding;
        /// <summary>Length of text in bytes</summary>
        public ushort TextLen;
        /// <summary>Fixed buffer for text</summary>
        [MarshalAs(UnmanagedType.ByValArray, SizeConst = 16)]
        public byte[] Content;
    }

    /// <summary>
    /// Multi-channel environmental sensor readings
    /// </summary>
    [StructLayout(LayoutKind.Sequential, Pack = 1)]
    public struct SensorReport {
        /// <summary>Unique sensor ID</summary>
        public uint SensorId;
        /// <summary>Temperature in Celsius</summary>
        public float Temperature;
        /// <summary>Pressure in hPa</summary>
        public float Pressure;
        /// <summary>Relative humidity (0.0 - 100.0)</summary>
        public float Humidity;
    }

    /// <summary>
    /// Polymorphic union container for choice `payload`.
    /// </summary>
    [StructLayout(LayoutKind.Explicit, Pack = 1)]
    public struct PayloadUnion {
        [FieldOffset(0)] public TextMessage TextMessage;
        [FieldOffset(0)] public SensorReport SensorReport;
    }

    /// <summary>
    /// Logical Name: footer
    /// Trailing CRC32 checksum verification
    /// Condition: flags & 0x01 != 0
    /// </summary>
    [StructLayout(LayoutKind.Sequential, Pack = 1)]
    public struct ChecksumFooter {
        /// <summary>IEEE 802.3 CRC32 checksum</summary>
        public uint Crc32;
    }

}