// ============================================================================
// Network Telemetry Protocol Specification
// Version: 1.0.0
// Unified binary messaging format supporting text messages and sensor telemetry packets.
// Automatically generated by binary_master.
// ============================================================================

package telemetry

// ============================================================================
// Protocol Overview & Scope
// ============================================================================
// This document specifies the Network Telemetry Protocol (NTP-v1).
// All multi-byte numeric fields are encoded in Little-Endian byte order.
//
// Packets begin with a fixed 14-byte `PacketHeader`. The `msg_type` field dictates
// which payload structure immediately follows:
// - `0x0001`: `TextMessage`
// - `0x0002`: `SensorReport`
//
// If bit 0 of `flags` is set (`flags & 0x01 != 0`), a 4-byte `ChecksumFooter` is appended.

// Logical Name: header
// Fixed 14-byte packet header
type PacketHeader struct {
	Magic uint32 // Signature: 0x4D534750 ('MSGP')
	Version uint16 // Protocol version
	MsgType uint16 // 1 = Text, 2 = Sensor Data
	PayloadSize uint32 // Length of following payload
	Flags uint16 // Bit 0: Has Checksum Footer
}

// PayloadTag represents tag values for choice payload (dispatched by msg_type).
// Dynamic payload dispatched by PacketHeader.msg_type
type PayloadTag uint16

const (
	PayloadTagTextMessage PayloadTag = 0x01 // Human-readable plaintext message payload
	PayloadTagSensorReport PayloadTag = 0x02 // Multi-channel environmental sensor readings
)

// Human-readable plaintext message payload
type TextMessage struct {
	Encoding uint16 // 1 = UTF-8, 2 = ASCII
	TextLen uint16 // Length of text in bytes
	Content [16]uint8 // Fixed buffer for text
}

// Multi-channel environmental sensor readings
type SensorReport struct {
	SensorId uint32 // Unique sensor ID
	Temperature float32 // Temperature in Celsius
	Pressure float32 // Pressure in hPa
	Humidity float32 // Relative humidity (0.0 - 100.0)
}

// Payload is the interface implemented by all variants of choice payload.
type Payload interface {
	IsPayload()
}

func (TextMessage) IsPayload() {}
func (SensorReport) IsPayload() {}

// Logical Name: footer
// Trailing CRC32 checksum verification
// Condition: flags & 0x01 != 0
type ChecksumFooter struct {
	Crc32 uint32 // IEEE 802.3 CRC32 checksum
}
