#ifndef NETWORK_TELEMETRY_PROTOCOL_SPECIFICATION_H
#define NETWORK_TELEMETRY_PROTOCOL_SPECIFICATION_H

/**
 * @file
 * @brief Network Telemetry Protocol Specification
 * @version 1.0.0
 * Unified binary messaging format supporting text messages and sensor telemetry packets.
 *
 * Automatically generated by binary_master.
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Force 1-byte struct alignment for exact binary wire format */
#if defined(_MSC_VER)
#pragma pack(push, 1)
#elif defined(__GNUC__) || defined(__clang__)
#pragma pack(push, 1)
#endif

/*
 * ============================================================================
 * Protocol Overview & Scope
 * ============================================================================
 * This document specifies the Network Telemetry Protocol (NTP-v1).
 * All multi-byte numeric fields are encoded in Little-Endian byte order.
 *
 * Packets begin with a fixed 14-byte `PacketHeader`. The `msg_type` field dictates
 * which payload structure immediately follows:
 * - `0x0001`: `TextMessage`
 * - `0x0002`: `SensorReport`
 *
 * If bit 0 of `flags` is set (`flags & 0x01 != 0`), a 4-byte `ChecksumFooter` is appended.
 */

/* ----------------------------------------------------------------------------
 * Section: Header Section
 * Fixed container identification header
 * ---------------------------------------------------------------------------- */

/**
 * @brief Logical Name: `header`
 * Fixed 14-byte packet header
 */
typedef struct PacketHeader {
    uint32_t magic; /**< Signature: 0x4D534750 ('MSGP') */
    uint16_t version; /**< Protocol version */
    uint16_t msg_type; /**< 1 = Text, 2 = Sensor Data */
    uint32_t payload_size; /**< Length of following payload */
    uint16_t flags; /**< Bit 0: Has Checksum Footer */
} PacketHeader;

/* ----------------------------------------------------------------------------
 * Section: Header Section
 * Fixed container identification header
 * ---------------------------------------------------------------------------- */

/* ----------------------------------------------------------------------------
 * Section: Payload Section
 * Polymorphic payload block
 * ---------------------------------------------------------------------------- */

/**
 * @brief Tag values for choice `payload` (dispatched by `msg_type`).
 * Dynamic payload dispatched by PacketHeader.msg_type
 */
typedef enum PayloadTag {
    PAYLOAD_TAG_TEXT_MESSAGE = 0x01, /**< Tag 0x01: Human-readable plaintext message payload */
    PAYLOAD_TAG_SENSOR_REPORT = 0x02, /**< Tag 0x02: Multi-channel environmental sensor readings */
} PayloadTag;

/**
 * Human-readable plaintext message payload
 */
typedef struct TextMessage {
    uint16_t encoding; /**< 1 = UTF-8, 2 = ASCII */
    uint16_t text_len; /**< Length of text in bytes */
    uint8_t content[16]; /**< Fixed buffer for text */
} TextMessage;

/**
 * Multi-channel environmental sensor readings
 */
typedef struct SensorReport {
    uint32_t sensor_id; /**< Unique sensor ID */
    float temperature; /**< Temperature in Celsius */
    float pressure; /**< Pressure in hPa */
    float humidity; /**< Relative humidity (0.0 - 100.0) */
} SensorReport;

/**
 * @brief Polymorphic union for choice `payload`.
 */
typedef union PayloadUnion {
    TextMessage text_message;
    SensorReport sensor_report;
} PayloadUnion;

/* ----------------------------------------------------------------------------
 * Section: Payload Section
 * Polymorphic payload block
 * ---------------------------------------------------------------------------- */

/* ----------------------------------------------------------------------------
 * Section: Footer Section
 * Optional trailing integrity verification
 * ---------------------------------------------------------------------------- */

/**
 * @brief Logical Name: `footer`
 * Trailing CRC32 checksum verification
 * @note Condition: flags & 0x01 != 0
 */
typedef struct ChecksumFooter {
    uint32_t crc32; /**< IEEE 802.3 CRC32 checksum */
} ChecksumFooter;

/* ----------------------------------------------------------------------------
 * Section: Footer Section
 * Optional trailing integrity verification
 * ---------------------------------------------------------------------------- */

#if defined(_MSC_VER) || defined(__GNUC__) || defined(__clang__)
#pragma pack(pop)
#endif

#ifdef __cplusplus
}
#endif

#endif /* NETWORK_TELEMETRY_PROTOCOL_SPECIFICATION_H */
