#pragma once

/**
 * @file
 * @brief Network Telemetry Protocol Specification
 * @version 1.0.0
 * テキスト通信と環境テレメトリ計測パケットを統合したバイナリプロトコル仕様。
 *
 * Automatically generated by binary_master.
 */

#include <cstdint>
#include <cstddef>
#include <array>
#include <variant>

/* Force 1-byte struct alignment */
#if defined(_MSC_VER)
#pragma pack(push, 1)
#elif defined(__GNUC__) || defined(__clang__)
#pragma pack(push, 1)
#endif

/*
 * ============================================================================
 * プロトコル概要とスコープ
 * ============================================================================
 * 本仕様書はネットワークテレメトリプロトコル (NTP-v1) を規定します。
 * すべての数値フィールドはリトルエンディアンでエンコードされます。
 *
 * パケットは固定14バイトの `PacketHeader` から開始し、`msg_type` に応じてペイロードが分岐します：
 * - `0x0001`: `TextMessage`
 * - `0x0002`: `SensorReport`
 *
 * また、`flags` の Bit 0 が立っている場合、末尾に 4 バイトの `ChecksumFooter` が付与されます。
 */

/* ----------------------------------------------------------------------------
 * Section: Header Section
 * コンテナ識別固定ヘッダー
 * ---------------------------------------------------------------------------- */

/**
 * @brief Logical Name: `header`
 * 固定14バイトパケットヘッダー
 */
struct PacketHeader {
    uint32_t magic;
    uint16_t version;
    uint16_t msg_type;
    uint32_t payload_size;
    uint16_t flags;
};

/* ----------------------------------------------------------------------------
 * Section: Header Section
 * コンテナ識別固定ヘッダー
 * ---------------------------------------------------------------------------- */

/* ----------------------------------------------------------------------------
 * Section: Payload Section
 * 動的ペイロードブロック
 * ---------------------------------------------------------------------------- */

/**
 * @brief Strongly-typed tag values for choice `payload` (dispatched by `msg_type`).
 * PacketHeader.msg_type による動的分岐
 */
enum class PayloadTag : uint16_t {
    TextMessage = 0x01, /**< Tag 0x01: プレーンテキストメッセージ */
    SensorReport = 0x02, /**< Tag 0x02: マルチチャネル環境センサー計測値 */
};

/**
 * プレーンテキストメッセージ
 */
struct TextMessage {
    uint16_t encoding;
    uint16_t text_len;
    std::array<uint8_t, 16> content;
};

/**
 * マルチチャネル環境センサー計測値
 */
struct SensorReport {
    uint32_t sensor_id;
    float temperature;
    float pressure;
    float humidity;
};

/**
 * @brief Type-safe variant container for choice `payload`.
 */
using PayloadVariant = std::variant<TextMessage, SensorReport>;

/* ----------------------------------------------------------------------------
 * Section: Payload Section
 * 動的ペイロードブロック
 * ---------------------------------------------------------------------------- */

/* ----------------------------------------------------------------------------
 * Section: Footer Section
 * オプション完全性検証ブロック
 * ---------------------------------------------------------------------------- */

/**
 * @brief Logical Name: `footer`
 * CRC32 チェックサム
 * @note Condition: flags & 0x01 != 0
 */
struct ChecksumFooter {
    uint32_t crc32;
};

/* ----------------------------------------------------------------------------
 * Section: Footer Section
 * オプション完全性検証ブロック
 * ---------------------------------------------------------------------------- */

#if defined(_MSC_VER) || defined(__GNUC__) || defined(__clang__)
#pragma pack(pop)
#endif
