#ifndef NETWORK_TELEMETRY_PROTOCOL_SPECIFICATION_H
#define NETWORK_TELEMETRY_PROTOCOL_SPECIFICATION_H

/**
 * @file
 * @brief Network Telemetry Protocol Specification
 * @version 1.0.0
 * テキスト通信と環境テレメトリ計測パケットを統合したバイナリプロトコル仕様。
 *
 * Automatically generated by binary_master.
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Force 1-byte struct alignment for exact binary wire format */
#if defined(_MSC_VER)
#pragma pack(push, 1)
#elif defined(__GNUC__) || defined(__clang__)
#pragma pack(push, 1)
#endif

/*
 * ============================================================================
 * プロトコル概要とスコープ
 * ============================================================================
 * 本仕様書はネットワークテレメトリプロトコル (NTP-v1) を規定します。
 * すべての数値フィールドはリトルエンディアンでエンコードされます。
 *
 * パケットは固定14バイトの `PacketHeader` から開始し、`msg_type` に応じてペイロードが分岐します：
 * - `0x0001`: `TextMessage`
 * - `0x0002`: `SensorReport`
 *
 * また、`flags` の Bit 0 が立っている場合、末尾に 4 バイトの `ChecksumFooter` が付与されます。
 */

/* ----------------------------------------------------------------------------
 * Section: Header Section
 * コンテナ識別固定ヘッダー
 * ---------------------------------------------------------------------------- */

/**
 * @brief Logical Name: `header`
 * 固定14バイトパケットヘッダー
 */
typedef struct PacketHeader {
    uint32_t magic;
    uint16_t version;
    uint16_t msg_type;
    uint32_t payload_size;
    uint16_t flags;
} PacketHeader;

/* ----------------------------------------------------------------------------
 * Section: Header Section
 * コンテナ識別固定ヘッダー
 * ---------------------------------------------------------------------------- */

/* ----------------------------------------------------------------------------
 * Section: Payload Section
 * 動的ペイロードブロック
 * ---------------------------------------------------------------------------- */

/**
 * @brief Tag values for choice `payload` (dispatched by `msg_type`).
 * PacketHeader.msg_type による動的分岐
 */
typedef enum PayloadTag {
    PAYLOAD_TAG_TEXT_MESSAGE = 0x01, /**< Tag 0x01: プレーンテキストメッセージ */
    PAYLOAD_TAG_SENSOR_REPORT = 0x02, /**< Tag 0x02: マルチチャネル環境センサー計測値 */
} PayloadTag;

/**
 * プレーンテキストメッセージ
 */
typedef struct TextMessage {
    uint16_t encoding;
    uint16_t text_len;
    uint8_t content[16];
} TextMessage;

/**
 * マルチチャネル環境センサー計測値
 */
typedef struct SensorReport {
    uint32_t sensor_id;
    float temperature;
    float pressure;
    float humidity;
} SensorReport;

/**
 * @brief Polymorphic union for choice `payload`.
 */
typedef union PayloadUnion {
    TextMessage text_message;
    SensorReport sensor_report;
} PayloadUnion;

/* ----------------------------------------------------------------------------
 * Section: Payload Section
 * 動的ペイロードブロック
 * ---------------------------------------------------------------------------- */

/* ----------------------------------------------------------------------------
 * Section: Footer Section
 * オプション完全性検証ブロック
 * ---------------------------------------------------------------------------- */

/**
 * @brief Logical Name: `footer`
 * CRC32 チェックサム
 * @note Condition: flags & 0x01 != 0
 */
typedef struct ChecksumFooter {
    uint32_t crc32;
} ChecksumFooter;

/* ----------------------------------------------------------------------------
 * Section: Footer Section
 * オプション完全性検証ブロック
 * ---------------------------------------------------------------------------- */

#if defined(_MSC_VER) || defined(__GNUC__) || defined(__clang__)
#pragma pack(pop)
#endif

#ifdef __cplusplus
}
#endif

#endif /* NETWORK_TELEMETRY_PROTOCOL_SPECIFICATION_H */
