#ifndef BINARY_PROTOCOL_H
#define BINARY_PROTOCOL_H

/**
 * @file
 * @brief Binary Protocol
 *
 * Automatically generated by binary_master.
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Force 1-byte struct alignment for exact binary wire format */
#if defined(_MSC_VER)
#pragma pack(push, 1)
#elif defined(__GNUC__) || defined(__clang__)
#pragma pack(push, 1)
#endif

/* ----------------------------------------------------------------------------
 * Section: File Header
 * Container header identifying format and version
 * ---------------------------------------------------------------------------- */

/* ----------------------------------------------------------------------------
 * Section: Metadata
 * Textual metadata and application properties
 * ---------------------------------------------------------------------------- */

/* ----------------------------------------------------------------------------
 * Section: Dynamic Payload
 * Dynamic payload dispatched by chunk_type
 * ---------------------------------------------------------------------------- */

/**
 * @brief Tag values for choice `payload` (dispatched by `chunk_type`).
 * Configuration header variant
 */
typedef enum PayloadTag {
    PAYLOAD_TAG_HEADER_CHUNK = 0x01, /**< Tag 0x01: Configuration header parameters. */
    PAYLOAD_TAG_TEXT_CHUNK = 0x02, /**< Tag 0x02: Text data chunk payload. */
} PayloadTag;

/**
 * Configuration header parameters.
 */
typedef struct HeaderChunk {
    uint16_t protocol_version;
    uint16_t flags;
} HeaderChunk;

/**
 * Text data chunk payload.
 */
typedef struct TextChunk {
    uint16_t length;
    uint8_t content[16];
} TextChunk;

/**
 * @brief Polymorphic union for choice `payload`.
 */
typedef union PayloadUnion {
    HeaderChunk header_chunk;
    TextChunk text_chunk;
} PayloadUnion;

/* ----------------------------------------------------------------------------
 * Section: DataRecord
 * ---------------------------------------------------------------------------- */

/**
 * Repeating measurement data record.
 */
typedef struct DataRecord {
    uint32_t record_id;
    uint32_t timestamp;
    float value;
} DataRecord;

#if defined(_MSC_VER) || defined(__GNUC__) || defined(__clang__)
#pragma pack(pop)
#endif

#ifdef __cplusplus
}
#endif

#endif /* BINARY_PROTOCOL_H */
