#ifndef BINARY_PROTOCOL_H
#define BINARY_PROTOCOL_H

/**
 * @file
 * @brief Binary Protocol
 *
 * Automatically generated by binary_master.
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Force 1-byte struct alignment for exact binary wire format */
#if defined(_MSC_VER)
#pragma pack(push, 1)
#elif defined(__GNUC__) || defined(__clang__)
#pragma pack(push, 1)
#endif

/* ----------------------------------------------------------------------------
 * Section: File Header
 * ファイル識別子とバージョン
 * ---------------------------------------------------------------------------- */

/* ----------------------------------------------------------------------------
 * Section: Metadata
 * アプリケーション属性テキスト
 * ---------------------------------------------------------------------------- */

/* ----------------------------------------------------------------------------
 * Section: Dynamic Payload
 * 動的ペイロードブロック
 * ---------------------------------------------------------------------------- */

/**
 * @brief Tag values for choice `payload` (dispatched by `chunk_type`).
 * Configuration header variant
 */
typedef enum PayloadTag {
    PAYLOAD_TAG_HEADER_CHUNK = 0x01, /**< Tag 0x01: HeaderChunk(protocol_version: binary_master.binary_types.UInt16, flags: binary_master.binary_types.UInt16) */
    PAYLOAD_TAG_TEXT_CHUNK = 0x02, /**< Tag 0x02: TextChunk(length: binary_master.binary_types.UInt16, content: (<class 'binary_master.binary_types.FixedArray'>, <class 'binary_master.binary_types.UInt8'>, 16)) */
} PayloadTag;

/**
 * HeaderChunk(protocol_version: binary_master.binary_types.UInt16, flags: binary_master.binary_types.UInt16)
 */
typedef struct HeaderChunk {
    uint16_t protocol_version;
    uint16_t flags;
} HeaderChunk;

/**
 * TextChunk(length: binary_master.binary_types.UInt16, content: (<class 'binary_master.binary_types.FixedArray'>, <class 'binary_master.binary_types.UInt8'>, 16))
 */
typedef struct TextChunk {
    uint16_t length;
    uint8_t content[16];
} TextChunk;

/**
 * @brief Polymorphic union for choice `payload`.
 */
typedef union PayloadUnion {
    HeaderChunk header_chunk;
    TextChunk text_chunk;
} PayloadUnion;

/* ----------------------------------------------------------------------------
 * Section: DataRecord
 * 連続計測データレコード
 * ---------------------------------------------------------------------------- */

/**
 * DataRecord(record_id: binary_master.binary_types.UInt32, timestamp: binary_master.binary_types.UInt32, value: binary_master.binary_types.Float32)
 */
typedef struct DataRecord {
    uint32_t record_id;
    uint32_t timestamp;
    float value;
} DataRecord;

#if defined(_MSC_VER) || defined(__GNUC__) || defined(__clang__)
#pragma pack(pop)
#endif

#ifdef __cplusplus
}
#endif

#endif /* BINARY_PROTOCOL_H */
