from typing import Literal

L = Literal


from .binary_struct import (
    Array,
    Base,
    BinaryEnum,
    BinaryStruct,
    BinaryType,
    Bits,
    Bool,
    Bytes,
    Constant,
    CountOf,
    CString,
    Double,
    FixedArray,
    FixedString,
    Float,
    Float16,
    Float32,
    Float64,
    Int8,
    Int16,
    Int32,
    Int64,
    LengthOf,
    Magic,
    NamedOffset,
    Offset,
    OffsetTable,
    PrefixedString,
    Range,
    RelativeBase,
    Struct,
    UInt8,
    UInt16,
    UInt32,
    UInt64,
    Variant,
    binary_size,
    binary_struct,
    bit_offsetof,
    from_bytes,
    offsetof,
    read_struct,
    sizeof,
    to_bytes,
    write_struct,
    write_variant,
)
from .bitstream import BitReader, BitWriter
from .builder import BinaryBuilder, Builder, BuilderReadResult
from .c_header import to_c_header, to_c_struct, write_c_header
from .checksum import (
    CRC16,
    CRC16_ARC,
    CRC16_CCITT,
    CRC32,
    Adler32,
    Checksum8,
    Checksum16,
    ChecksumBase,
    Fletcher16,
    compute_checksum,
)
from .code_gen import (
    generate_code,
    generate_cpp_code,
    generate_csharp_code,
    generate_go_code,
    generate_rust_code,
    write_code,
    write_cpp,
    write_csharp,
    write_go,
    write_rust,
)
from .debug import (
    debug_dump,
    diff_dump,
    dump_dict,
    dump_json,
    dump_table,
    hexdump,
)
from .enums import Endian, EndianType, normalize_endian, normalize_named_offset_key
from .exceptions import (
    BinaryMasterError,
    ChecksumMismatchError,
    DuplicateNamedOffsetError,
    InvalidConstantError,
    InvalidEnumError,
    InvalidMagicError,
    NamedOffsetError,
    NamedOffsetNotFoundError,
    RangeValidationError,
    TotalSizeExceededError,
)
from .manual import (
    LayoutEntry,
    generate_bitfield_packet_diagram,
    generate_html,
    generate_manual,
    generate_mermaid_diagram,
    generate_packet_diagram,
    inspect_struct_layout,
    resolve_language,
    write_html,
)
from .reader import BinaryReader, Reader
from .varint import (
    VarInt,
    VarInt32,
    VarInt64,
    VarUInt,
    VarUInt32,
    VarUInt64,
    decode_varint,
    decode_varuint,
    encode_varint,
    encode_varuint,
)
from .writer import BinaryWriter, OffsetTableHandle, Writer

__version__ = "0.3.8"


__all__ = [
    "BinaryWriter",
    "Writer",
    "BinaryReader",
    "Reader",
    "OffsetTableHandle",
    "Endian",
    "EndianType",
    "normalize_endian",
    "BinaryType",
    "UInt8",
    "UInt16",
    "UInt32",
    "UInt64",
    "Int8",
    "Int16",
    "Int32",
    "Int64",
    "Float16",
    "Float32",
    "Float64",
    "Float",
    "Double",
    "Bool",
    "Bytes",
    "FixedString",
    "CString",
    "PrefixedString",
    "Offset",
    "NamedOffset",
    "OffsetTable",
    "Variant",
    "Array",
    "FixedArray",
    "Bits",
    "Base",
    "RelativeBase",
    "BinaryEnum",
    "Magic",
    "Constant",
    "Range",
    "LengthOf",
    "CountOf",
    "BinaryMasterError",
    "ChecksumMismatchError",
    "InvalidMagicError",
    "InvalidConstantError",
    "InvalidEnumError",
    "RangeValidationError",
    "TotalSizeExceededError",
    "NamedOffsetError",
    "DuplicateNamedOffsetError",
    "NamedOffsetNotFoundError",
    "normalize_named_offset_key",
    "ChecksumBase",
    "CRC32",
    "CRC16",
    "CRC16_CCITT",
    "CRC16_ARC",
    "Checksum8",
    "Checksum16",
    "Fletcher16",
    "Adler32",
    "compute_checksum",
    "VarUInt",
    "VarInt",
    "VarUInt32",
    "VarInt32",
    "VarUInt64",
    "VarInt64",
    "encode_varuint",
    "decode_varuint",
    "encode_varint",
    "decode_varint",
    "BitWriter",
    "BitReader",
    "binary_struct",
    "BinaryStruct",
    "Struct",
    "write_struct",
    "write_variant",
    "read_struct",
    "to_bytes",
    "from_bytes",
    "sizeof",
    "binary_size",
    "offsetof",
    "bit_offsetof",
    "LayoutEntry",
    "generate_manual",
    "generate_html",
    "write_html",
    "generate_mermaid_diagram",
    "generate_packet_diagram",
    "generate_bitfield_packet_diagram",
    "inspect_struct_layout",
    "resolve_language",
    "BinaryBuilder",

    "Builder",
    "BuilderReadResult",
    "to_c_header",
    "write_c_header",
    "to_c_struct",
    "generate_code",
    "write_code",
    "generate_rust_code",
    "write_rust",
    "generate_cpp_code",
    "write_cpp",
    "generate_csharp_code",
    "write_csharp",
    "generate_go_code",
    "write_go",
    "hexdump",
    "debug_dump",
    "diff_dump",
    "dump_table",
    "dump_json",
    "dump_dict",
    "Literal",
    "L",
]



